import { Dialogue } from './types';

export const DIALOGUES: Dialogue[] = [
  {
    "id": "1",
    "characterFull": "Rancho",
    "actor": "Aamir Khan",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "All is well.",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "2",
    "characterFull": "Virus",
    "actor": "Boman Irani",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "Life is a race.",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "3",
    "characterFull": "Ranchoddas Shamaldas Chanchad (Rancho)",
    "actor": "Aamir Khan",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "All izz well.",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "4",
    "characterFull": "Professor Viru Sahastrabudhhe (Virus)",
    "actor": "Boman Irani",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "Pressure vs learning — harsh principal lines (paraphrase)",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "5",
    "characterFull": "Rancho",
    "actor": "Aamir Khan",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "Success ke peeche mat bhago, excellence ka peecha karo... success jhak maar ke tumhare peeche aayegi.",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Hard",
    "isPopular": true
  },
  {
    "id": "6",
    "characterFull": "Farhan Qureshi",
    "actor": "R. Madhavan",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "Dost fail ho jaye toh dukh hota hai, lekin dost first aa jaye toh zyada dukh hota hai.",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Hard",
    "isPopular": true
  },
  {
    "id": "7",
    "characterFull": "Rancho/Farhan/Raju",
    "actor": "Aamir/Madhavan/Sharman",
    "movieFull": "3 Idiots (2009)",
    "dialogue": "Jahapanah tussi great ho, tohfa kubool karo.",
    "era": "2000s",
    "genre": "Comedy",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "8",
    "characterFull": "Kapil Dev",
    "actor": "Ranveer Singh",
    "movieFull": "83 (2021)",
    "dialogue": "We are here to win.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "9",
    "characterFull": "Common Man",
    "actor": "Naseeruddin Shah",
    "movieFull": "A Wednesday (2008)",
    "dialogue": "I am just a stupid common man.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "10",
    "characterFull": "Rahul",
    "actor": "Aditya Roy Kapur",
    "movieFull": "Aashiqui 2 (2013)",
    "dialogue": "Pyaar, mohabbat, aashiqui sirf lafzon ke siva aur kuch nahi...",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "11",
    "characterFull": "Ayan",
    "actor": "Ranbir Kapoor",
    "movieFull": "Ae Dil Hai Mushkil (2016)",
    "dialogue": "Ek tarfa pyaar ki taqat hi kuch aur hoti hai... uspar kisi aur ka haq nahi hota.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "12",
    "characterFull": "Ayan",
    "actor": "Ranbir Kapoor",
    "movieFull": "Ae Dil Hai Mushkil (2016)",
    "dialogue": "Pyar dosti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "13",
    "characterFull": "Vijay Dinanath Chauhan",
    "actor": "Amitabh Bachchan",
    "movieFull": "Agneepath (1990)",
    "dialogue": "Naam Vijay Dinanath Chauhan.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "14",
    "characterFull": "Vijay Chauhan",
    "actor": "Hrithik Roshan",
    "movieFull": "Agneepath (2012)",
    "dialogue": "Naam Vijay Dinanath Chauhan, poora naam.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "15",
    "characterFull": "Amar",
    "actor": "Aamir Khan",
    "movieFull": "Andaz Apna Apna (1994)",
    "dialogue": "Teja main hoon, mark idhar hai.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "16",
    "characterFull": "Crime Master Gogo",
    "actor": "Shakti Kapoor",
    "movieFull": "Andaz Apna Apna (1994)",
    "dialogue": "Aankhen nikaal ke gotiyan khelunga.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "17",
    "characterFull": "Prem",
    "actor": "Salman Khan",
    "movieFull": "Andaz Apna Apna (1994)",
    "dialogue": "Do dost ek cup mein chai piyenge.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "18",
    "characterFull": "Akash Saraf",
    "actor": "Ayushmann Khurrana",
    "movieFull": "Andhadhun (2018)",
    "dialogue": "Kala aadmi ko bahut kuch deti hai ... lekin TDS bhi poora kaat leti hai",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "19",
    "characterFull": "Akash",
    "actor": "Ayushmann Khurrana",
    "movieFull": "Andhadhun (2018)",
    "dialogue": "Kuch cheezein aisi hoti hain, jo sirf andhe dekh sakte hain.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "20",
    "characterFull": "Ranvijay Singh",
    "actor": "Ranbir Kapoor",
    "movieFull": "Animal (2023)",
    "dialogue": "Papa ke liye kuch bhi.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "21",
    "characterFull": "Ranvijay",
    "actor": "Ranbir Kapoor",
    "movieFull": "Animal (2023)",
    "dialogue": "You are my father, and I am your son.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "22",
    "characterFull": "Ranvijay",
    "actor": "Ranbir Kapoor",
    "movieFull": "Animal (2023)",
    "dialogue": "Papa ko kuch mat bolna.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "23",
    "characterFull": "Ranvijay",
    "actor": "Ranbir Kapoor",
    "movieFull": "Animal (2023)",
    "dialogue": "My love for you is unconditional.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "24",
    "characterFull": "Ayan Ranjan",
    "actor": "Ayushmann Khurrana",
    "movieFull": "Article 15 (2019)",
    "dialogue": "Hum unhe Harijan bolte hain aur woh hume unka bhagwan samajhte hain.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "25",
    "characterFull": "Raj",
    "actor": "Shah Rukh Khan",
    "movieFull": "Baazigar (1993)",
    "dialogue": "Kabhi kabhi jeetne ke liye kuch haarna padta hai.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "26",
    "characterFull": "Nakul",
    "actor": "Ayushmann Khurrana",
    "movieFull": "Badhaai Ho (2018)",
    "dialogue": "Bhaijaan, family ki baat alag hoti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "27",
    "characterFull": "Badrinath",
    "actor": "Varun Dhawan",
    "movieFull": "Badrinath Ki Dulhania (2017)",
    "dialogue": "Pyar ka hisaab maths ke isoolon par nahi chalta.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "28",
    "characterFull": "Bajirao",
    "actor": "Ranveer Singh",
    "movieFull": "Bajirao Mastani (2015)",
    "dialogue": "Bajirao ne Mastani se mohabbat ki hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "29",
    "characterFull": "Peshwa Bajirao",
    "actor": "Ranveer Singh",
    "movieFull": "Bajirao Mastani (2015)",
    "dialogue": "Cheete ki chal, baaj ki najar or bajirao ki talwar pe kabhi sandeh nahin krte, kabhi bhi mat de skti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "30",
    "characterFull": "Bajirao",
    "actor": "Ranveer Singh",
    "movieFull": "Bajirao Mastani (2015)",
    "dialogue": "Bajirao ne Mastani se mohabbat ki hai, aiyashi nahi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "31",
    "characterFull": "Mastani",
    "actor": "Deepika Padukone",
    "movieFull": "Bajirao Mastani (2015)",
    "dialogue": "Aapne dil maanga hota toh de dete, aapne toh hamara guroor hi maang liya.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "32",
    "characterFull": "Kashibai",
    "actor": "Priyanka Chopra",
    "movieFull": "Bajirao Mastani (2015)",
    "dialogue": "Kashibai ki jaan nikale toh bhi aapki dhadkan mein Kashi ka naam dhadkega.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "33",
    "characterFull": "Bajirao",
    "actor": "Ranveer Singh",
    "movieFull": "Bajirao Mastani (2015)",
    "dialogue": "Cheete ki chaal, baaz ki nazar, aur Bajirao ki talwar par sandeh nahi karte.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "34",
    "characterFull": "Pavan Kumar Chaturvedi",
    "actor": "Salman Khan",
    "movieFull": "Bajrangi Bhaijaan (2015)",
    "dialogue": "Main us bachchi ko wapas uske ghar le jaunga.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "35",
    "characterFull": "Bajrangi (Bajrangi Bhaijaan)",
    "actor": "Salman Khan",
    "movieFull": "Bajrangi Bhaijaan (2015)",
    "dialogue": "I will take her home — heartfelt line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "36",
    "characterFull": "Murphy \"Barfi\" Johnson",
    "actor": "Ranbir Kapoor",
    "movieFull": "Barfi! (2012)",
    "dialogue": "Life mein sabse bada risk hota hai… koi risk na lena.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "37",
    "characterFull": "Rana",
    "actor": "Farhan Akhtar",
    "movieFull": "Bhaag Milkha Bhaag (2013)",
    "dialogue": "Run like your life depends on it — training line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "38",
    "characterFull": "Milkha Singh",
    "actor": "Farhan Akhtar",
    "movieFull": "Bhaag Milkha Bhaag (2013)",
    "dialogue": "Run! — iconic training push",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "39",
    "characterFull": "Milkha Singh",
    "actor": "Farhan Akhtar",
    "movieFull": "Bhaag Milkha Bhaag (2013)",
    "dialogue": "Yeh aapki aakhri race ho sakti hai. Daudunga bhi waise hi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "40",
    "characterFull": "Debraj Sahai",
    "actor": "Amitabh Bachchan",
    "movieFull": "Black (2005)",
    "dialogue": "Teaching with patience — famous mentor dialogue",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "41",
    "characterFull": "Shiva",
    "actor": "Ranbir Kapoor",
    "movieFull": "Brahmastra (2022)",
    "dialogue": "Kaun ho tum? Main aag hoon.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "42",
    "characterFull": "Isha",
    "actor": "Alia Bhatt",
    "movieFull": "Brahmastra (2022)",
    "dialogue": "Kuch rishte aag aur dhuen jaise hote hain.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "43",
    "characterFull": "Bunty",
    "actor": "Abhishek Bachchan",
    "movieFull": "Bunty Aur Babli (2005)",
    "dialogue": "Duniya mein do tarah ke log hote hain...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "44",
    "characterFull": "Kabir Khan",
    "actor": "Unknown",
    "movieFull": "Chak De India (2007)",
    "dialogue": "Sattar minute.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "45",
    "characterFull": "Kabir Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chak De! India (2007)",
    "dialogue": "Chak de India!",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "46",
    "characterFull": "Kabir Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chak De! India (2007)",
    "dialogue": "Sattar minute, sattar minute hai tumhare paas.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "47",
    "characterFull": "Kabir Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chak De! India (2007)",
    "dialogue": "Mujhe states ke naam na sunai dete hain na dikhai dete hain...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "48",
    "characterFull": "Kabir Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chak De! India (2007)",
    "dialogue": "Vaar karna hai toh samne wale ke goal par nahi, uske dimaag par karo.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "49",
    "characterFull": "Rahul Mithaiwala",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chennai Express (2013)",
    "dialogue": "Unexpected journey to the south — comedic line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "50",
    "characterFull": "Rahul",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chennai Express (2013)",
    "dialogue": "Don't underestimate the power of a common man.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "51",
    "characterFull": "Meenamma",
    "actor": "Deepika Padukone",
    "movieFull": "Chennai Express (2013)",
    "dialogue": "Kahan se kharidi aisi bakwas dictionary?",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "52",
    "characterFull": "Rahul",
    "actor": "Shah Rukh Khan",
    "movieFull": "Chennai Express (2013)",
    "dialogue": "Ready steady po!",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "53",
    "characterFull": "Anni",
    "actor": "Sushant Singh Rajput",
    "movieFull": "Chhichhore (2019)",
    "dialogue": "Hum haar jeet, success failure mein itne ulajh gaye hain ki zindagi jeena bhool gaye hain.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "54",
    "characterFull": "Sexa",
    "actor": "Varun Sharma",
    "movieFull": "Chhichhore (2019)",
    "dialogue": "Sachche dost woh hote hain jo tumhari beizzati mein bhi saath khade hote hain.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "55",
    "characterFull": "Chulbul Pandey",
    "actor": "Unknown",
    "movieFull": "Dabangg (2010)",
    "dialogue": "Thappad se darr nahi lagta sahab.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "56",
    "characterFull": "Chulbul Pandey",
    "actor": "Salman Khan",
    "movieFull": "Dabangg (2010)",
    "dialogue": "Swagat nahi karoge hamara?",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "57",
    "characterFull": "Rajjo",
    "actor": "Sonakshi Sinha",
    "movieFull": "Dabangg (2010)",
    "dialogue": "Thappad se darr nahi lagta sahab, pyaar se lagta hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "58",
    "characterFull": "Chulbul Pandey",
    "actor": "Salman Khan",
    "movieFull": "Dabangg (2010)",
    "dialogue": "Hum yahan ke Robinhood hain... Robinhood Pandey.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "59",
    "characterFull": "Makhi",
    "actor": "Arbaaz Khan",
    "movieFull": "Dabangg (2010)",
    "dialogue": "Kamaal karte ho Pandey ji.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "60",
    "characterFull": "Mahavir Singh Phogat",
    "actor": "Aamir Khan",
    "movieFull": "Dangal (2016)",
    "dialogue": "Train your daughters to be champions (paraphrase)",
    "era": "2010s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "61",
    "characterFull": "Mahavir Singh Phogat",
    "actor": "Aamir Khan",
    "movieFull": "Dangal (2016)",
    "dialogue": "Mhari chhoriyan chhoron se kam hain ke?",
    "era": "2010s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "62",
    "characterFull": "Mahavir Singh Phogat",
    "actor": "Aamir Khan",
    "movieFull": "Dangal (2016)",
    "dialogue": "Medal ped pe nahi ughte, unhe banana padta hai...",
    "era": "2010s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "63",
    "characterFull": "Mahavir Singh Phogat",
    "actor": "Aamir Khan",
    "movieFull": "Dangal (2016)",
    "dialogue": "Gold toh gold hota hai, chhora laave ya chhori.",
    "era": "2010s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "64",
    "characterFull": "Dr. Jehangir Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Dear Zindagi (2016)",
    "dialogue": "Don't let the past blackmail your present to ruin a beautiful future.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "65",
    "characterFull": "Dr. Jehangir Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Dear Zindagi (2016)",
    "dialogue": "Hum itni kursiyan dekhte hain kharidne se pehle, toh life partner choose karne se pehle options kyun nahi?",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "66",
    "characterFull": "Devdas Mukherjee",
    "actor": "Shah Rukh Khan",
    "movieFull": "Devdas (2002)",
    "dialogue": "Kaun kambakht bardaasht karne ke liye peeta hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "67",
    "characterFull": "Devdas",
    "actor": "Shah Rukh Khan",
    "movieFull": "Devdas (2002)",
    "dialogue": "Babuji ne kaha gaon chhod do… sab ne kaha Paro ko chhod do… Paro ne kaha sharab chhod do. Aaj tumne keh diya haweli chhod do… ek din aayega jab woh kahenge, duniya hi chhod do",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "68",
    "characterFull": "Devdas",
    "actor": "Shah Rukh Khan",
    "movieFull": "Devdas (2002)",
    "dialogue": "Aurat maa hoti hai, behen hoti hai, patni hoti hai, dost hoti hai...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "69",
    "characterFull": "Paro",
    "actor": "Aishwarya Rai",
    "movieFull": "Devdas (2002)",
    "dialogue": "Kitni aasani se ginwa diya ki naukre ki daulat mere dard se badi hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "70",
    "characterFull": "Adi",
    "actor": "Arshad Warsi",
    "movieFull": "Dhamaal (2007)",
    "dialogue": "Paisa kahan hai W ke neeche?",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "71",
    "characterFull": "Sahir",
    "actor": "Aamir Khan",
    "movieFull": "Dhoom 3 (2013)",
    "dialogue": "Bande hain hum uske, hum pe kiska zor.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "72",
    "characterFull": "Akash Malhotra",
    "actor": "Aamir Khan",
    "movieFull": "Dil Chahta Hai (2001)",
    "dialogue": "Long drives and friendship — famous vibe",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "73",
    "characterFull": "Sameer Mulchandani",
    "actor": "Saif Ali Khan",
    "movieFull": "Dil Chahta Hai (2001)",
    "dialogue": "Friendship banter and witty lines",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "74",
    "characterFull": "Akash",
    "actor": "Aamir Khan",
    "movieFull": "Dil Chahta Hai (2001)",
    "dialogue": "Ya toh dosti gehri hai, ya yeh photo 3D hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "75",
    "characterFull": "Zoya / Meera",
    "actor": "Kajol/Alia",
    "movieFull": "Dilwale (2015)",
    "dialogue": "Dil toh har kisi ke paas hota hai… lekin sab dilwale nahi hote.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "76",
    "characterFull": "Raj Malhotra",
    "actor": "Unknown",
    "movieFull": "Dilwale Dulhania Le Jayenge (1995)",
    "dialogue": "Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hain.",
    "era": "1990s",
    "genre": "Romance",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "77",
    "characterFull": "Simran Kaur",
    "actor": "Kajol",
    "movieFull": "Dilwale Dulhania Le Jayenge (1995)",
    "dialogue": "Palat!",
    "era": "1990s",
    "genre": "Romance",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "78",
    "characterFull": "Don",
    "actor": "Amitabh Bachchan",
    "movieFull": "Don (1978)",
    "dialogue": "Don ko pakadna mushkil hi nahi, namumkin hai.",
    "era": "1900s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "79",
    "characterFull": "Don",
    "actor": "Shah Rukh Khan",
    "movieFull": "Don 2 (2011)",
    "dialogue": "Don ke dushman ki sabse badi ghalti yeh hai ki wo Don ka dushman hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "80",
    "characterFull": "Kabir",
    "actor": "Ajay Devgn",
    "movieFull": "Drishyam (2015)",
    "dialogue": "2 October, panaji, satsang of swami, pav bhaji, ATM",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "81",
    "characterFull": "Vijay Salgaonkar",
    "actor": "Ajay Devgn",
    "movieFull": "Drishyam 2 (2022)",
    "dialogue": "Sach jhooth se zyada tikta nahi hai.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "82",
    "characterFull": "Hardy",
    "actor": "Shah Rukh Khan",
    "movieFull": "Dunki (2023)",
    "dialogue": "Koi bhi apna ghar nahi chhodna chahta, jab tak ki uska ghar uska dushman na ban jaye.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "83",
    "characterFull": "Avinash \"Tiger\" Rathore",
    "actor": "Salman Khan",
    "movieFull": "Ek Tha Tiger (2012)",
    "dialogue": "Shikar toh sab karte hain… lekin tiger se behtar shikar koi nahi karta.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "84",
    "characterFull": "Zoya",
    "actor": "Katrina Kaif",
    "movieFull": "Ek Tha Tiger (2012)",
    "dialogue": "Jis mohabbat mein deewangi na ho ... woh mohabbat hi nahi",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "85",
    "characterFull": "Tiger",
    "actor": "Salman Khan",
    "movieFull": "Ek Tha Tiger (2012)",
    "dialogue": "Sher soya hua hai, usko mat jagao.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "86",
    "characterFull": "Guru",
    "actor": "Sidharth Malhotra",
    "movieFull": "Ek Villain (2014)",
    "dialogue": "Andhere ko andhera nahi, sirf roshni mita sakti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "87",
    "characterFull": "Meghna Mathur",
    "actor": "Priyanka Chopra",
    "movieFull": "Fashion (2008)",
    "dialogue": "Success ki seedhi chadte waqt dhyaan rakhna chahiye...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "88",
    "characterFull": "Tara Singh",
    "actor": "Sunny Deol",
    "movieFull": "Gadar 2 (2023)",
    "dialogue": "Tara Singh ko mat chhedna.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "89",
    "characterFull": "Tara Singh",
    "actor": "Sunny Deol",
    "movieFull": "Gadar 2 (2023)",
    "dialogue": "Ghar aaja pardesi, tera des bulaye re... bajne de is baar.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "90",
    "characterFull": "Ramadhir Singh",
    "actor": "Tigmanshu Dhulia",
    "movieFull": "Gangs of Wasseypur (2012)",
    "dialogue": "Tumse na ho payega.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "91",
    "characterFull": "Faizal Khan",
    "actor": "Nawazuddin Siddiqui",
    "movieFull": "Gangs of Wasseypur (2012)",
    "dialogue": "Baap ka, dada ka, bhai ka, sabka badla lega re tera Faizal.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "92",
    "characterFull": "Ramadhir Singh",
    "actor": "Tigmanshu Dhulia",
    "movieFull": "Gangs of Wasseypur (2012)",
    "dialogue": "Jab tak is desh mein cinema hai, log chutiye bante rahenge.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "93",
    "characterFull": "Sardar Khan",
    "actor": "Manoj Bajpayee",
    "movieFull": "Gangs of Wasseypur (2012)",
    "dialogue": "Goli nahi marenge, keh ke lenge.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "94",
    "characterFull": "Faizal Khan",
    "actor": "Nawazuddin Siddiqui",
    "movieFull": "Gangs of Wasseypur (2012)",
    "dialogue": "Permission leni chahiye thi na.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "95",
    "characterFull": "Gangubai",
    "actor": "Alia Bhatt",
    "movieFull": "Gangubai Kathiawadi (2022)",
    "dialogue": "Izzat se jeene ka, kisi se darne ka nahi.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "96",
    "characterFull": "Gangubai",
    "actor": "Alia Bhatt",
    "movieFull": "Gangubai Kathiawadi (2022)",
    "dialogue": "Gangu chaand thi, aur chaand hi rahegi.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "97",
    "characterFull": "Sanjay Singhania",
    "actor": "Aamir Khan",
    "movieFull": "Ghajini (2008)",
    "dialogue": "Vishvas aur ghamund mein bahut kum farak hai ... main kar sakta hoon, yeh mera vishvas hai ... sirf main hi kar sakta hoon, yeh mera ghamund",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "98",
    "characterFull": "Ram",
    "actor": "Ranveer Singh",
    "movieFull": "Goliyon Ki Raasleela Ram-Leela (2013)",
    "dialogue": "Jigar pe mat jaa, trigger daba dunga.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "99",
    "characterFull": "Dr. Joshi",
    "actor": "Adil Hussain",
    "movieFull": "Good Newwz (2019)",
    "dialogue": "Aapki wife ki report mein error nahi, terror hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "100",
    "characterFull": "Murad Ahmed (MC Sher)",
    "actor": "Ranveer Singh",
    "movieFull": "Gully Boy (2019)",
    "dialogue": "From the gutters to the stage — rap rise line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "101",
    "characterFull": "Murad",
    "actor": "Ranveer Singh",
    "movieFull": "Gully Boy (2019)",
    "dialogue": "Apna time aayega.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "102",
    "characterFull": "Safeena",
    "actor": "Alia Bhatt",
    "movieFull": "Gully Boy (2019)",
    "dialogue": "Mere boyfriend se gulu gulu karegi toh dhoptungi na usko.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "103",
    "characterFull": "MC Sher",
    "actor": "Siddhant Chaturvedi",
    "movieFull": "Gully Boy (2019)",
    "dialogue": "Tum agar sab kuch thik hone ka wait karoge, toh apni poori life ushi mein nikal jayegi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "104",
    "characterFull": "Haider",
    "actor": "Shahid Kapoor",
    "movieFull": "Haider (2014)",
    "dialogue": "Hum hain ki hum nahi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "105",
    "characterFull": "Charlie",
    "actor": "Shah Rukh Khan",
    "movieFull": "Happy New Year (2014)",
    "dialogue": "Kismat badi kutti cheez hai, saali kabhi bhi palat sakti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "106",
    "characterFull": "Baburao Ganpatrao Apte",
    "actor": "Paresh Rawal",
    "movieFull": "Hera Pheri (2000)",
    "dialogue": "Utha le re baba.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "107",
    "characterFull": "Raju",
    "actor": "Akshay Kumar",
    "movieFull": "Hera Pheri (2000)",
    "dialogue": "Yeh Babu Rao ka style hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "108",
    "characterFull": "Shyam",
    "actor": "Suniel Shetty",
    "movieFull": "Hera Pheri (2000)",
    "dialogue": "Paisa hi paisa hoga.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "109",
    "characterFull": "Raj",
    "actor": "Irrfan Khan",
    "movieFull": "Hindi Medium (2017)",
    "dialogue": "My life is Hindi, but my wife is English.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "110",
    "characterFull": "Prem",
    "actor": "Salman Khan",
    "movieFull": "Hum Aapke Hain Koun..! (1994)",
    "dialogue": "Dosti ka ek usool hai madam.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "111",
    "characterFull": "Sameer",
    "actor": "Salman Khan",
    "movieFull": "Hum Dil De Chuke Sanam (1999)",
    "dialogue": "Agar tum mujhe yun hi dekhti rahi ... toh tumhe mujhse pyar ho jayega",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "112",
    "characterFull": "Nandini",
    "actor": "Aishwarya Rai",
    "movieFull": "Hum Dil De Chuke Sanam (1999)",
    "dialogue": "Kabhi kabhi insaan kuch nahi kehkar bhi ... sab kuch keh deta hai",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "113",
    "characterFull": "Aditya Kashyap",
    "actor": "Shahid Kapoor",
    "movieFull": "Jab We Met (2007)",
    "dialogue": "Train miss ho gayi.",
    "era": "2000s",
    "genre": "Romance",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "114",
    "characterFull": "Geet",
    "actor": "Unknown",
    "movieFull": "Jab We Met (2007)",
    "dialogue": "Main apni favorite hoon.",
    "era": "2000s",
    "genre": "Romance",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "115",
    "characterFull": "Geet Dhillon",
    "actor": "Kareena Kapoor",
    "movieFull": "Jab We Met (2007)",
    "dialogue": "Main apni favourite hoon.",
    "era": "2000s",
    "genre": "Romance",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "116",
    "characterFull": "Geet Dhillon",
    "actor": "Kareena Kapoor",
    "movieFull": "Jab We Met (2007)",
    "dialogue": "Sikhni hoon main Bhatinda ki.",
    "era": "2000s",
    "genre": "Romance",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "117",
    "characterFull": "Station Master",
    "actor": "Asif Basra",
    "movieFull": "Jab We Met (2007)",
    "dialogue": "Akeli ladki khuli hui tijori ki tarah hoti hai.",
    "era": "2000s",
    "genre": "Romance",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "118",
    "characterFull": "Aditya Kashyap",
    "actor": "Shahid Kapoor",
    "movieFull": "Jab We Met (2007)",
    "dialogue": "Jo kuch insaan chahta hai, agar wo usey dil se mange... toh ho hi jata hai.",
    "era": "2000s",
    "genre": "Romance",
    "difficulty": "Hard",
    "isPopular": true
  },
  {
    "id": "119",
    "characterFull": "Vikram Rathore",
    "actor": "Shah Rukh Khan",
    "movieFull": "Jawan (2023)",
    "dialogue": "Bete ko haath lagane se pehle, baap se baat kar.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "120",
    "characterFull": "Vikram Rathore",
    "actor": "Shah Rukh Khan",
    "movieFull": "Jawan (2023)",
    "dialogue": "Jab main villain banta hoon, toh koi hero mere saamne tik nahi pata.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "121",
    "characterFull": "Vikram Rathore",
    "actor": "Shah Rukh Khan",
    "movieFull": "Jawan (2023)",
    "dialogue": "Chahiye toh Alia Bhatt, par umar mein thodi chhoti hai.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "122",
    "characterFull": "Rahul Raichand",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kabhi Khushi Kabhie Gham (2001)",
    "dialogue": "Keh diya na… bas keh diya.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "123",
    "characterFull": "Rahul Raichand",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kabhi Khushi Kabhie Gham (2001)",
    "dialogue": "It is all about family.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "124",
    "characterFull": "Pooja (Poo)",
    "actor": "Kareena Kapoor",
    "movieFull": "Kabhi Khushi Kabhie Gham (2001)",
    "dialogue": "A sassy, iconic one-liner (stylish attitude)",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "125",
    "characterFull": "Poo",
    "actor": "Kareena Kapoor",
    "movieFull": "Kabhi Khushi Kabhie Gham (2001)",
    "dialogue": "Kaun hai yeh, jisne dobara mud ke mujhe nahi dekha? Who is he?",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "126",
    "characterFull": "Yashvardhan Raichand",
    "actor": "Amitabh Bachchan",
    "movieFull": "Kabhi Khushi Kabhie Gham (2001)",
    "dialogue": "Keh diya na, bas keh diya.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "127",
    "characterFull": "Kabir Singh",
    "actor": "Shahid Kapoor",
    "movieFull": "Kabir Singh (2019)",
    "dialogue": "Main banda hi kharaab hoon.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "128",
    "characterFull": "Kabir Singh",
    "actor": "Shahid Kapoor",
    "movieFull": "Kabir Singh (2019)",
    "dialogue": "I will not let go of my love (intense line)",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "129",
    "characterFull": "Kabir Singh",
    "actor": "Shahid Kapoor",
    "movieFull": "Kabir Singh (2019)",
    "dialogue": "Preeti meri hai!",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "130",
    "characterFull": "Kabir Singh",
    "actor": "Shahid Kapoor",
    "movieFull": "Kabir Singh (2019)",
    "dialogue": "I am not a rebel without a cause.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "131",
    "characterFull": "Vidya Bagchi",
    "actor": "Vidya Balan",
    "movieFull": "Kahaani (2012)",
    "dialogue": "A pregnant woman searching for her husband in Kolkata",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "132",
    "characterFull": "Rohit",
    "actor": "Hrithik Roshan",
    "movieFull": "Kaho Naa... Pyaar Hai (2000)",
    "dialogue": "Pyaar kiya nahi jaata… ho jaata hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "133",
    "characterFull": "Aman Mathur",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Aaj ek hasi aur baant lo.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "134",
    "characterFull": "Aman Mathur",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Aaj… aaj ek hasi aur baant lo.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "135",
    "characterFull": "Aman Mathur",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Live for today — key life line",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "136",
    "characterFull": "Naina Talwar",
    "actor": "Preity Zinta",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Live for today — heartfelt line",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "137",
    "characterFull": "Aman Mathur",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Jiyo, khush raho, muskurao... kya pata kal ho naa ho.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "138",
    "characterFull": "Aman Mathur",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Pyaar toh bahut log karte hain, lekin mere jaisa pyaar koi nahi kar sakta...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "139",
    "characterFull": "Aman Mathur",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kal Ho Naa Ho (2003)",
    "dialogue": "Main aankhein band karta hoon toh tumhe dekhta hoon, aankhein kholta hoon toh tumhe dekhna chahta hoon. Tum paas nahin hoti toh tumhe charon taraf mehsoos karta hoon. Har pal har ghadi har waqt mere naina meri Naina ko doondhte hain.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "140",
    "characterFull": "Devi Lal Singh",
    "actor": "Salman Khan",
    "movieFull": "Kick (2014)",
    "dialogue": "Mere bare mein itna mat sochna, dil mein aata hoon, samajh mein nahi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "141",
    "characterFull": "Devi Lal Singh",
    "actor": "Salman Khan",
    "movieFull": "Kick (2014)",
    "dialogue": "Aap devil ke peeche, devil aapke peeche... Too much fun.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "142",
    "characterFull": "Rohit Mehra",
    "actor": "Hrithik Roshan",
    "movieFull": "Koi... Mil Gaya (2003)",
    "dialogue": "Dhoop.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "143",
    "characterFull": "Rohit Mehra",
    "actor": "Hrithik Roshan",
    "movieFull": "Koi... Mil Gaya (2003)",
    "dialogue": "Magical friendship with an alien (short hint)",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "144",
    "characterFull": "Rohit",
    "actor": "Hrithik Roshan",
    "movieFull": "Koi... Mil Gaya (2003)",
    "dialogue": "Mujhe kuch dikhai nahi de raha maa.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "145",
    "characterFull": "Krishna Mehra",
    "actor": "Hrithik Roshan",
    "movieFull": "Krrish (2006)",
    "dialogue": "Hero woh hota hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "146",
    "characterFull": "Rohan (Hero)",
    "actor": "Hrithik Roshan",
    "movieFull": "Krrish (2006)",
    "dialogue": "Superhero reveal — brief heroic line",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "147",
    "characterFull": "Rahul Khanna",
    "actor": "Unknown",
    "movieFull": "Kuch Kuch Hota Hai (1998)",
    "dialogue": "Kuch kuch hota hai tum nahi samjhogi.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "148",
    "characterFull": "Rahul Khanna",
    "actor": "Shah Rukh Khan",
    "movieFull": "Kuch Kuch Hota Hai (1998)",
    "dialogue": "Kuch kuch hota hai — tum nahi samjhogi.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "149",
    "characterFull": "Anjali Sharma",
    "actor": "Kajol",
    "movieFull": "Kuch Kuch Hota Hai (1998)",
    "dialogue": "I love you, friend.",
    "era": "1990s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "150",
    "characterFull": "Bhuvan",
    "actor": "Aamir Khan",
    "movieFull": "Lagaan (2001)",
    "dialogue": "Hum jeetenge.",
    "era": "2000s",
    "genre": "Sports",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "151",
    "characterFull": "Bhuvan Singh",
    "actor": "Aamir Khan",
    "movieFull": "Lagaan (2001)",
    "dialogue": "Let us play cricket — versus the British.",
    "era": "2000s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "152",
    "characterFull": "Gauri",
    "actor": "Gracy Singh",
    "movieFull": "Lagaan (2001)",
    "dialogue": "Supportive village spirit — iconic scene",
    "era": "2000s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "153",
    "characterFull": "Captain Russell",
    "actor": "Paul Blackthorne",
    "movieFull": "Lagaan (2001)",
    "dialogue": "Teen guna lagaan dena padega.",
    "era": "2000s",
    "genre": "Sports",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "154",
    "characterFull": "Murli Prasad \"Munna Bhai\" Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Lage Raho Munna Bhai (2006)",
    "dialogue": "Gandhigiri karna seekho.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "155",
    "characterFull": "Murli Prasad Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Lage Raho Munna Bhai (2006)",
    "dialogue": "Bole toh, Gandhigiri.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "156",
    "characterFull": "Murli Prasad Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Lage Raho Munna Bhai (2006)",
    "dialogue": "Desh toh apna ho gaya hai, par log paraye ho gaye hain.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "157",
    "characterFull": "Sattu Bhaiya",
    "actor": "Pankaj Tripathi",
    "movieFull": "Ludo (2020)",
    "dialogue": "Ludo is life, life is Ludo.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "158",
    "characterFull": "Ram Prasad Sharma",
    "actor": "Shah Rukh Khan",
    "movieFull": "Main Hoon Na (2004)",
    "dialogue": "Nafrat ko sirf mohabbat se jeeta jaa sakta hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "159",
    "characterFull": "Ram Prasad Sharma",
    "actor": "Shah Rukh Khan",
    "movieFull": "Main Hoon Na (2004)",
    "dialogue": "Mera naam Ram hai, Ram Prasad Sharma.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "160",
    "characterFull": "Raj Aryan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Mohabbatein (2000)",
    "dialogue": "Mohabbat bhi zindagi ki tarah hoti hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "161",
    "characterFull": "Circuit",
    "actor": "Arshad Warsi",
    "movieFull": "Munna Bhai M.B.B.S. (2003)",
    "dialogue": "Bhai ne bola karne ka matlab karne ka.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "162",
    "characterFull": "Murli Prasad Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Munna Bhai M.B.B.S. (2003)",
    "dialogue": "Jaadu ki jhappi.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "163",
    "characterFull": "Murli Prasad \"Munna Bhai\" Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Munna Bhai M.B.B.S. (2003)",
    "dialogue": "Jadoo ki jhappi.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "164",
    "characterFull": "Murli Prasad Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Munna Bhai M.B.B.S. (2003)",
    "dialogue": "Tension lene ka nahi, sirf dene ka.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "165",
    "characterFull": "Rustom's Father",
    "actor": "Kurush Deboo",
    "movieFull": "Munna Bhai M.B.B.S. (2003)",
    "dialogue": "Carrom ramwanu, juice pivanu, majja ni life.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "166",
    "characterFull": "Murli Prasad Sharma",
    "actor": "Sanjay Dutt",
    "movieFull": "Munna Bhai M.B.B.S. (2003)",
    "dialogue": "Woh bahar casualty mein koi marne ki halat mein raha toh usko form bharna zaroori hai kya?",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "167",
    "characterFull": "Rizwan Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "My Name Is Khan (2010)",
    "dialogue": "My name is Khan, and I am not a terrorist.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "168",
    "characterFull": "Rizwan Khan",
    "actor": "Shah Rukh Khan",
    "movieFull": "My Name Is Khan (2010)",
    "dialogue": "Duniya mein sirf do tarah ke insaan hote hain... acche aur bure.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "169",
    "characterFull": "Om Kapoor",
    "actor": "Shah Rukh Khan",
    "movieFull": "Om Shanti Om (2007)",
    "dialogue": "Picture abhi baaki hai mere dost.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "170",
    "characterFull": "Om Prakash Makhija / Om Kapoor",
    "actor": "Shah Rukh Khan",
    "movieFull": "Om Shanti Om (2007)",
    "dialogue": "Itni shiddat se maine tumhe paane ki koshish ki hai... ki har zarre ne mujhe tumse milane ki saazish ki hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "171",
    "characterFull": "Shantipriya",
    "actor": "Deepika Padukone",
    "movieFull": "Om Shanti Om (2007)",
    "dialogue": "Ek chutki sindoor ki keemat tum kya jano Ramesh babu.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "172",
    "characterFull": "Om Prakash Makhija",
    "actor": "Shah Rukh Khan",
    "movieFull": "Om Shanti Om (2007)",
    "dialogue": "Kehte hain agar kisi cheez ko dil se chaho, toh poori kainaat usse tumse milane ki koshish mein lag jaati hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "173",
    "characterFull": "Om Prakash Makhija",
    "actor": "Shah Rukh Khan",
    "movieFull": "Om Shanti Om (2007)",
    "dialogue": "Hamari filmon ki tarah hamari zindagi mein bhi end tak sab theek ho hi jaata hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "174",
    "characterFull": "Langda Tyagi",
    "actor": "Saif Ali Khan",
    "movieFull": "Omkara (2006)",
    "dialogue": "Betrayal and vengeance — iconic menace",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "175",
    "characterFull": "Ajay Devgn character (Omkara)",
    "actor": "Ajay Devgn",
    "movieFull": "Omkara (2006)",
    "dialogue": "Raw and rustic betrayal hint",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "176",
    "characterFull": "Sultan Mirza",
    "actor": "Ajay Devgn",
    "movieFull": "Once Upon a Time in Mumbaai (2010)",
    "dialogue": "Dua mein yaad rakhna.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "177",
    "characterFull": "Sultan Mirza",
    "actor": "Ajay Devgn",
    "movieFull": "Once Upon a Time in Mumbaai (2010)",
    "dialogue": "Jab dost banake kaam ho sakta hai toh dushman kyun banaye.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "178",
    "characterFull": "Alauddin Khilji",
    "actor": "Ranveer Singh",
    "movieFull": "Padmaavat (2018)",
    "dialogue": "Khilji ke paas dimaag bhi hai.",
    "era": "2010s",
    "genre": "Action",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "179",
    "characterFull": "Padmavati",
    "actor": "Deepika Padukone",
    "movieFull": "Padmaavat (2018)",
    "dialogue": "Rajputi kangan mein utni hi taqat hai jitni Rajputi talwar mein.",
    "era": "2010s",
    "genre": "Action",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "180",
    "characterFull": "Maharawal Ratan Singh",
    "actor": "Shahid Kapoor",
    "movieFull": "Padmaavat (2018)",
    "dialogue": "Keh dijiye apne sultan se, unki talwar se zyada dhar hamare tevar mein hai.",
    "era": "2010s",
    "genre": "Action",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "181",
    "characterFull": "Alauddin Khilji",
    "actor": "Ranveer Singh",
    "movieFull": "Padmaavat (2018)",
    "dialogue": "Alauddin ke paas sabkuch hai, bas ek Rajput ka dil nahi hai.",
    "era": "2010s",
    "genre": "Action",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "182",
    "characterFull": "Maharawal Ratan Singh",
    "actor": "Shahid Kapoor",
    "movieFull": "Padmaavat (2018)",
    "dialogue": "Jab Rajput apne desh, apni dharti ke liye ladta hai, toh maut bhi usse ghabrati hai.",
    "era": "2010s",
    "genre": "Action",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "183",
    "characterFull": "Pathaan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Pathaan (2023)",
    "dialogue": "Party Pathaan ke ghar rakhoge toh mehmaannawazi ke liye Pathaan toh aayega.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "184",
    "characterFull": "Pathaan",
    "actor": "Shah Rukh Khan",
    "movieFull": "Pathaan (2023)",
    "dialogue": "Ek soldier ye nahi poochta ki desh ne uske liye kya kiya...",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "185",
    "characterFull": "Babu Bhaiya",
    "actor": "Paresh Rawal",
    "movieFull": "Phir Hera Pheri (2006)",
    "dialogue": "Yeh toh shuru hote hi khatam ho gaya.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "186",
    "characterFull": "Raju",
    "actor": "Akshay Kumar",
    "movieFull": "Phir Hera Pheri (2006)",
    "dialogue": "Paisa laya?",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "187",
    "characterFull": "Raju",
    "actor": "Akshay Kumar",
    "movieFull": "Phir Hera Pheri (2006)",
    "dialogue": "Zor zor bolke logon ko schemein bata de!",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "188",
    "characterFull": "Kachra Seth",
    "actor": "Manoj Joshi",
    "movieFull": "Phir Hera Pheri (2006)",
    "dialogue": "Dedh sau rupiya dega.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "189",
    "characterFull": "Shyam",
    "actor": "Suniel Shetty",
    "movieFull": "Phir Hera Pheri (2006)",
    "dialogue": "Mere anuradha aisi nahi hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "190",
    "characterFull": "Rana",
    "actor": "Irrfan Khan",
    "movieFull": "Piku (2015)",
    "dialogue": "Death aur shit... ye do cheezein kisi ko bhi, kahin bhi, kabhi bhi aa sakti hain.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "191",
    "characterFull": "Bhaskor Banerjee",
    "actor": "Amitabh Bachchan",
    "movieFull": "Piku (2015)",
    "dialogue": "Insaan ka emotion uska motion ke saath juda hua hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "192",
    "characterFull": "Deepak Sehgal",
    "actor": "Amitabh Bachchan",
    "movieFull": "Pink (2016)",
    "dialogue": "'No' is a complete sentence.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "193",
    "characterFull": "PK",
    "actor": "Aamir Khan",
    "movieFull": "PK (2014)",
    "dialogue": "Wrong number.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "194",
    "characterFull": "PK (name unknown)",
    "actor": "Aamir Khan",
    "movieFull": "PK (2014)",
    "dialogue": "Why do people follow rituals? (curious outsider)",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "195",
    "characterFull": "PK",
    "actor": "Aamir Khan",
    "movieFull": "PK (2014)",
    "dialogue": "Kaun sa wrong number pe call lag gaya hai?",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "196",
    "characterFull": "PK",
    "actor": "Aamir Khan",
    "movieFull": "PK (2014)",
    "dialogue": "Ee gola pe ehi to confusion hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "197",
    "characterFull": "Rajat",
    "actor": "Kartik Aaryan",
    "movieFull": "Pyaar Ka Punchnama (2011)",
    "dialogue": "Problem yeh hai ki main chahta hoon meri life mein koi problem na ho.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "198",
    "characterFull": "Rani Mehra",
    "actor": "Kangana Ranaut",
    "movieFull": "Queen (2014)",
    "dialogue": "I will go on my own honeymoon — self-discovery line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "199",
    "characterFull": "Rani",
    "actor": "Kangana Ranaut",
    "movieFull": "Queen (2014)",
    "dialogue": "Finding yourself after heartbreak",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "200",
    "characterFull": "Rani",
    "actor": "Kangana Ranaut",
    "movieFull": "Queen (2014)",
    "dialogue": "Mera toh itna life kharab ho gaya hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "201",
    "characterFull": "Rani",
    "actor": "Kangana Ranaut",
    "movieFull": "Queen (2014)",
    "dialogue": "Indian ladkiyan best hoti hain.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "202",
    "characterFull": "Rohit (cameo)",
    "actor": "Shah Rukh Khan",
    "movieFull": "Ra.One (2011)",
    "dialogue": "Burai sang joh mel rachaya ... phir kabhi na chutte uska saaya",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "203",
    "characterFull": "Kundan",
    "actor": "Dhanush",
    "movieFull": "Raanjhanaa (2013)",
    "dialogue": "Namaz mein wo thi, par dua hamari qubool ho gayi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "204",
    "characterFull": "Kundan",
    "actor": "Dhanush",
    "movieFull": "Raanjhanaa (2013)",
    "dialogue": "Aashiq ki aadhi jaan toh uski sacchi kahani banne mein nikal jati hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "205",
    "characterFull": "Raees",
    "actor": "Shah Rukh Khan",
    "movieFull": "Raees (2017)",
    "dialogue": "Ammi jaan kehti thi, koi dhanda chhota nahi hota aur dhande se bada koi dharam nahi hota.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "206",
    "characterFull": "Raees",
    "actor": "Shah Rukh Khan",
    "movieFull": "Raees (2017)",
    "dialogue": "Baniye ka dimaag aur miyanbhai ki daring.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "207",
    "characterFull": "Raees",
    "actor": "Shah Rukh Khan",
    "movieFull": "Raees (2017)",
    "dialogue": "Agar dhanda shanti se chal raha ho toh use chhedne ka nahi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "208",
    "characterFull": "DJ",
    "actor": "Aamir Khan",
    "movieFull": "Rang De Basanti (2006)",
    "dialogue": "Koi bhi desh perfect nahi hota, usse perfect banana padta hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "209",
    "characterFull": "DJ",
    "actor": "Aamir Khan",
    "movieFull": "Rang De Basanti (2006)",
    "dialogue": "Ab bhi jiska khoon na khaula, khoon nahi wo paani hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "210",
    "characterFull": "Jordan",
    "actor": "Unknown",
    "movieFull": "Rockstar (2011)",
    "dialogue": "Dard bhi ek tarah ka pyaar hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "211",
    "characterFull": "Janardan \"Jordan\" Jakhar",
    "actor": "Ranbir Kapoor",
    "movieFull": "Rockstar (2011)",
    "dialogue": "I sing my pain — raw musician vibe",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "212",
    "characterFull": "Khatana",
    "actor": "Kumud Mishra",
    "movieFull": "Rockstar (2011)",
    "dialogue": "Toote hue dil se hi sangeet nikalta hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "213",
    "characterFull": "Rocky",
    "actor": "Ranveer Singh",
    "movieFull": "Rocky Aur Rani Kii Prem Kahaani (2023)",
    "dialogue": "Pyaar kiya toh darna kya, aur pyaar karke shaadi nahi karna toh kya karna?",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "214",
    "characterFull": "Shiva",
    "actor": "Akshay Kumar",
    "movieFull": "Rowdy Rathore (2012)",
    "dialogue": "Don't angry me.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "215",
    "characterFull": "Shiva",
    "actor": "Akshay Kumar",
    "movieFull": "Rowdy Rathore (2012)",
    "dialogue": "Jo main bolta hoon wo main karta hoon, aur jo main nahi bolta wo main definitely karta hoon.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "216",
    "characterFull": "Alluri Sitarama Raju",
    "actor": "Ram Charan",
    "movieFull": "RRR (2022)",
    "dialogue": "Ladki se baat karne ke liye rasta dhoondte nahi ... khud banate hai",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "217",
    "characterFull": "Sanju",
    "actor": "Ranbir Kapoor",
    "movieFull": "Sanju (2018)",
    "dialogue": "Ustaad, wo bahar log marne wale hain...",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "218",
    "characterFull": "Sunil Dutt",
    "actor": "Paresh Rawal",
    "movieFull": "Sanju (2018)",
    "dialogue": "Mera beta badmash hai, par terrorist nahi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "219",
    "characterFull": "Kamli",
    "actor": "Vicky Kaushal",
    "movieFull": "Sanju (2018)",
    "dialogue": "Tiger hai tu Tiger... Roar!",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "220",
    "characterFull": "Vikram Batra",
    "actor": "Sidharth Malhotra",
    "movieFull": "Shershaah (2021)",
    "dialogue": "Yeh dil maange more!",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "221",
    "characterFull": "Vikram Batra",
    "actor": "Sidharth Malhotra",
    "movieFull": "Shershaah (2021)",
    "dialogue": "Ya toh Tiranga lehra ke aaunga, ya phir usmein lipat ke aaunga.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "222",
    "characterFull": "Gabbar Singh",
    "actor": "Amjad Khan",
    "movieFull": "Sholay (1975)",
    "dialogue": "Kitne aadmi the?",
    "era": "1900s",
    "genre": "Action",
    "difficulty": "Easy",
    "isPopular": true
  },
  {
    "id": "223",
    "characterFull": "Jai",
    "actor": "Amitabh Bachchan",
    "movieFull": "Sholay (1975)",
    "dialogue": "Tumhara naam kya hai Basanti?",
    "era": "1900s",
    "genre": "Action",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "224",
    "characterFull": "Veeru",
    "actor": "Dharmendra",
    "movieFull": "Sholay (1975)",
    "dialogue": "Basanti, in kutton ke saamne mat naachna.",
    "era": "1900s",
    "genre": "Action",
    "difficulty": "Medium",
    "isPopular": true
  },
  {
    "id": "225",
    "characterFull": "Simmba",
    "actor": "Ranveer Singh",
    "movieFull": "Simmba (2018)",
    "dialogue": "Joh deto traas, tyancha mi gheto class",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "226",
    "characterFull": "Bajirao Singham",
    "actor": "Ajay Devgn",
    "movieFull": "Singham (2011)",
    "dialogue": "Aata majhi satakli.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "227",
    "characterFull": "Bajirao Singham",
    "actor": "Ajay Devgn",
    "movieFull": "Singham (2011)",
    "dialogue": "Kismein kitna hai dum...",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "228",
    "characterFull": "Veer Sooryavanshi",
    "actor": "Akshay Kumar",
    "movieFull": "Sooryavanshi (2021)",
    "dialogue": "Fight terrorism with style (short line)",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "229",
    "characterFull": "Veer Sooryavanshi",
    "actor": "Akshay Kumar",
    "movieFull": "Sooryavanshi (2021)",
    "dialogue": "Yeh Mumbai police hai, inke nishane se aaj tak koi bach nahi paya hai.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "230",
    "characterFull": "Vicky",
    "actor": "Rajkummar Rao",
    "movieFull": "Stree (2018)",
    "dialogue": "O Stree kal aana.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "231",
    "characterFull": "Vicky",
    "actor": "Rajkummar Rao",
    "movieFull": "Stree (2018)",
    "dialogue": "Wo stree hai, wo kuch bhi kar sakti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "232",
    "characterFull": "Sultan Ali Khan",
    "actor": "Salman Khan",
    "movieFull": "Sultan (2016)",
    "dialogue": "Koi tumhe tab tak nahi hara sakta.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "233",
    "characterFull": "Sultan Ali Khan",
    "actor": "Salman Khan",
    "movieFull": "Sultan (2016)",
    "dialogue": "I will come back stronger — comeback line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "234",
    "characterFull": "Sultan (boxing)",
    "actor": "Salman Khan",
    "movieFull": "Sultan (2016)",
    "dialogue": "I will fight for her — vow line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "235",
    "characterFull": "Sultan",
    "actor": "Salman Khan",
    "movieFull": "Sultan (2016)",
    "dialogue": "Sultan ko sirf ek hi aadmi hara sakta hai, aur woh hai Sultan khud.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "236",
    "characterFull": "Sultan",
    "actor": "Salman Khan",
    "movieFull": "Sultan (2016)",
    "dialogue": "Asli pehlwaan ki pehchaan akhade mein nahi, zindagi mein hoti hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "237",
    "characterFull": "Anand Kumar",
    "actor": "Hrithik Roshan",
    "movieFull": "Super 30 (2019)",
    "dialogue": "Ab raja ka beta raja nahi banega, raja wahi banega jo haqdaar hoga.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "238",
    "characterFull": "Anand Kumar",
    "actor": "Hrithik Roshan",
    "movieFull": "Super 30 (2019)",
    "dialogue": "Udaan toh bharni hi hai, chahe kitni baar bhi girna pade.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "239",
    "characterFull": "Mohan Bhargava",
    "actor": "Shah Rukh Khan",
    "movieFull": "Swades (2004)",
    "dialogue": "Main nahi manta ki hamara desh duniya ka sabse mahaan desh hai… lekin yeh zaroor manta hoon ki hum mein usse mahaan banane ki kshamata hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "240",
    "characterFull": "Ishaan Awasthi",
    "actor": "Darsheel Safary",
    "movieFull": "Taare Zameen Par (2007)",
    "dialogue": "Ma'am the letters are dancing.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "241",
    "characterFull": "Ram Shankar Nikumbh",
    "actor": "Aamir Khan",
    "movieFull": "Taare Zameen Par (2007)",
    "dialogue": "Har bachche ki apni ek khasiyat hoti hai, apni ek taqat hoti hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "242",
    "characterFull": "Ved",
    "actor": "Ranbir Kapoor",
    "movieFull": "Tamasha (2015)",
    "dialogue": "Ek din main bilkul theek ho jaunga.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "243",
    "characterFull": "Ved",
    "actor": "Ranbir Kapoor",
    "movieFull": "Tamasha (2015)",
    "dialogue": "Bachpan se hi acting ka shauk hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "244",
    "characterFull": "Tanhaji",
    "actor": "Ajay Devgn",
    "movieFull": "Tanhaji (2020)",
    "dialogue": "Har Maratha pagal hai, Swaraj ka, Shivaji Raje ka.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "245",
    "characterFull": "Tanhaji",
    "actor": "Ajay Devgn",
    "movieFull": "Tanhaji (2020)",
    "dialogue": "Ghamand nahi, garv hai mujhe apne Maratha hone par.",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "246",
    "characterFull": "Tanhaji Malusare",
    "actor": "Ajay Devgn",
    "movieFull": "Tanhaji: The Unsung Warrior (2020)",
    "dialogue": "Bravery in battle — short heroic line",
    "era": "2020s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "247",
    "characterFull": "Datto",
    "actor": "Kangana Ranaut",
    "movieFull": "Tanu Weds Manu Returns (2015)",
    "dialogue": "Kya Sharma ji, hum thode bewafa kya hue, aap toh badchalan hi ho gaye.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "248",
    "characterFull": "Pappi",
    "actor": "Deepak Dobriyal",
    "movieFull": "Tanu Weds Manu Returns (2015)",
    "dialogue": "Adrak ho gaya hai ye aadmi, kahin se bhi badh raha hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "249",
    "characterFull": "Test Character",
    "actor": "tEST ACTOR",
    "movieFull": "Test Movie",
    "dialogue": "Test Dialogue",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "250",
    "characterFull": "Silk",
    "actor": "Vidya Balan",
    "movieFull": "The Dirty Picture (2011)",
    "dialogue": "Filmein sirf teen cheezon ki wajah se chalti hain: entertainment, entertainment, entertainment.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "251",
    "characterFull": "Silk",
    "actor": "Vidya Balan",
    "movieFull": "The Dirty Picture (2011)",
    "dialogue": "Jab zindagi ek baar mili hai, toh do baar kyun soche?",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "252",
    "characterFull": "Tiger",
    "actor": "Salman Khan",
    "movieFull": "Tiger Zinda Hai (2017)",
    "dialogue": "Shikaar toh sab karte hain, lekin Tiger se behtar shikaar koi nahi karta.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "253",
    "characterFull": "Keshav",
    "actor": "Akshay Kumar",
    "movieFull": "Toilet: Ek Prem Katha (2017)",
    "dialogue": "Aashiqon ne toh aashiqui mein Taj Mahal bana diya, hum ek sandas na bana sake.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "254",
    "characterFull": "Major Vihaan Singh Shergill",
    "actor": "Vicky Kaushal",
    "movieFull": "Uri: The Surgical Strike (2019)",
    "dialogue": "Aaj humne jawab diya.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "255",
    "characterFull": "Major Vihaan",
    "actor": "Vicky Kaushal",
    "movieFull": "Uri: The Surgical Strike (2019)",
    "dialogue": "How's the josh? High Sir!",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "256",
    "characterFull": "Major Vihaan",
    "actor": "Vicky Kaushal",
    "movieFull": "Uri: The Surgical Strike (2019)",
    "dialogue": "Yeh naya India hai. Yeh ghar mein ghusega bhi aur marega bhi.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "257",
    "characterFull": "Major Vihaan",
    "actor": "Vicky Kaushal",
    "movieFull": "Uri: The Surgical Strike (2019)",
    "dialogue": "Unhe Kashmir chahiye, aur hume unka sar.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "258",
    "characterFull": "Veer Pratap Singh",
    "actor": "Shah Rukh Khan",
    "movieFull": "Veer-Zaara (2004)",
    "dialogue": "Sachi mohabbat zindagi mein sirf ek baar hoti hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "259",
    "characterFull": "Siddharth Mehra (Sid)",
    "actor": "Ranbir Kapoor",
    "movieFull": "Wake Up Sid (2009)",
    "dialogue": "Main apne dad ke bagair kya hoon? Meri khud ki pehchan kya h…Mujhe nahi pata mujhe naukri karni hai. Main janta hoon mujhe kuchh nahi aata, pata nahi mujhe kaun naukri dega. Par ab mujhe kaam karna hai bas",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "260",
    "characterFull": "Sid",
    "actor": "Ranbir Kapoor",
    "movieFull": "Wake Up Sid (2009)",
    "dialogue": "Goal toh mera ek hi hai... kuch ban jaaun.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "261",
    "characterFull": "Radhe",
    "actor": "Unknown",
    "movieFull": "Wanted (2009)",
    "dialogue": "Ek baar jo maine commitment kar di.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "262",
    "characterFull": "Radhe",
    "actor": "Salman Khan",
    "movieFull": "Wanted (2009)",
    "dialogue": "Tu ladki ke peeche bhagega, ladki paise ke peeche bhagegi...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "263",
    "characterFull": "Kabir (Agent Kabir)",
    "actor": "Hrithik Roshan",
    "movieFull": "War (2019)",
    "dialogue": "Stylish agent action — short taunt",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "264",
    "characterFull": "Kabir",
    "actor": "Hrithik Roshan",
    "movieFull": "War (2019)",
    "dialogue": "Ghar mein ghuske marunga.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "265",
    "characterFull": "Majnu Bhai",
    "actor": "Anil Kapoor",
    "movieFull": "Welcome (2007)",
    "dialogue": "Control Uday control.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "266",
    "characterFull": "Uday Shetty",
    "actor": "Nana Patekar",
    "movieFull": "Welcome (2007)",
    "dialogue": "Bhagwan ka diya sab kuch hai.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "267",
    "characterFull": "Uday Shetty",
    "actor": "Nana Patekar",
    "movieFull": "Welcome (2007)",
    "dialogue": "Control Uday, control.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "268",
    "characterFull": "Uday Shetty",
    "actor": "Nana Patekar",
    "movieFull": "Welcome (2007)",
    "dialogue": "Aloo lelo, kanda lelo...",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "269",
    "characterFull": "Majnu Bhai",
    "actor": "Anil Kapoor",
    "movieFull": "Welcome (2007)",
    "dialogue": "Seh lenge thoda.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "270",
    "characterFull": "Rajiv",
    "actor": "Akshay Kumar",
    "movieFull": "Welcome (2007)",
    "dialogue": "Miracle, miracle!",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "271",
    "characterFull": "Uday Shetty",
    "actor": "Nana Patekar",
    "movieFull": "Welcome (2007)",
    "dialogue": "Subah se na ek aloo bika hai, na bika hai aadha kanda.",
    "era": "2000s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "272",
    "characterFull": "Bunny",
    "actor": "Ranbir Kapoor",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Main udna chahta hoon.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "273",
    "characterFull": "Naina Talwar",
    "actor": "Deepika Padukone",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Kahin pahunchne ke liye kahin se nikalna zaroori hota hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "274",
    "characterFull": "Bunny",
    "actor": "Ranbir Kapoor",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Travel and dreams — famous line hint",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "275",
    "characterFull": "Bunny",
    "actor": "Ranbir Kapoor",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Kahin pe pahunchne ke liye kahin se nikalna bahut zaroori hota hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "276",
    "characterFull": "Bunny",
    "actor": "Ranbir Kapoor",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Main udna chahta hoon, daudna chahta hoon... bas rukna nahi chahta.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "277",
    "characterFull": "Bunny",
    "actor": "Ranbir Kapoor",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Tum pehle bhi itni khoobsurat thi ya waqt ne kiya koi haseen sitam?",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "278",
    "characterFull": "Naina",
    "actor": "Deepika Padukone",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Kuch logon ke saath sirf waqt bitane se hi sab theek ho jata hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "279",
    "characterFull": "Naina",
    "actor": "Deepika Padukone",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Yaadein mithai ke dibbe ki tarah hoti hain, ek baar khula toh sirf ek tukda nahi kha paoge.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "280",
    "characterFull": "Bunny",
    "actor": "Ranbir Kapoor",
    "movieFull": "Yeh Jawaani Hai Deewani (2013)",
    "dialogue": "Waqt rukta nahi, beet jata hai.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "281",
    "characterFull": "Bauaa Singh",
    "actor": "Shah Rukh Khan",
    "movieFull": "Zero (2018)",
    "dialogue": "Zindagi mein jab zero bada ho jaata hai, toh hero banne mein time nahi lagta.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Hard",
    "isPopular": false
  },
  {
    "id": "282",
    "characterFull": "Arjun",
    "actor": "Hrithik Roshan",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Seize the day.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "283",
    "characterFull": "Imran",
    "actor": "Farhan Akhtar",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Pighle neelam sa.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "284",
    "characterFull": "Kabir Dewan",
    "actor": "Abhay Deol",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Shaadi kar raha hoon.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Easy",
    "isPopular": false
  },
  {
    "id": "285",
    "characterFull": "Arjun Saluja",
    "actor": "Hrithik Roshan",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Conquer your fear — famous vacation line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "286",
    "characterFull": "Arjun",
    "actor": "Hrithik Roshan",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Seize the day — famous line",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "287",
    "characterFull": "Imran",
    "actor": "Farhan Akhtar",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Dilon mein tum apni betabiyan leke chal rahe ho toh zinda ho tum.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "288",
    "characterFull": "Laila",
    "actor": "Katrina Kaif",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Seize the day my friend.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "289",
    "characterFull": "Imran",
    "actor": "Farhan Akhtar",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Insaan ka kartavya hota hai koshish karna.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  },
  {
    "id": "290",
    "characterFull": "Kabir",
    "actor": "Abhay Deol",
    "movieFull": "Zindagi Na Milegi Dobara (2011)",
    "dialogue": "Apne kaam ko apna junoon bana lo.",
    "era": "2010s",
    "genre": "Drama",
    "difficulty": "Medium",
    "isPopular": false
  }
];
